### ISSUE TITLE
该项目只是一个后端项目？

### ISSUE THREAD

**Issue by Timoshao** [xingxin666/chatgpt-nodejs-web#3]
请问大佬，该项目只是一个后端项目吗？
前端需要自己写吗？

**Comment by xingxin666** [comment]
页面参考 https://github.com/Chanzhaoyu/chatgpt-web

**Comment by Timoshao** [comment]
> 页面参考 https://github.com/Chanzhaoyu/chatgpt-web

现在我用的就是这个项目。不是开发人员，只会按照教程部署，所以不会写一个前端对接
